filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php:
        indentation:
            general:
                size: 2
        spaces:
            general:
                linefeed_character: newline
            around_operators:
                concatenation: false
            other:
                after_type_cast: false
        braces:
            classes_functions:
                class: undefined
                function: undefined
                closure: undefined
            switch:
                opening: undefined
            try:
                opening: undefined
        upper_lower_casing:
            keywords:
                general: undefined
            constants:
                true_false_null: undefined
build:
    nodes:
        tests: true
        analysis:
            tests:
                override:
                    -
                        command: phpcs-run
                        use_website_config: true
                    - php-scrutinizer-run